"""
Threat model definition for Model W Django + SvelteKit platform.
This is used to model the system architecture and identify potential security threats
using the pytm library and produce the required report and media.
"""

from pytm import (
    TM,
    Actor,
    Boundary,
    Classification,
    Data,
    Dataflow,
    Datastore,
    DatastoreType,
    ExternalEntity,
    Lifetime,
    Process,
    TLSVersion,
)

tm = TM("Model W Django + SvelteKit Platform - Comprehensive Threat Model")
tm.description = """
Comprehensive threat model for Model W project generator and generated projects.

This threat model covers:
1. The Model W Project Maker tool itself
2. Projects generated by the tool (Django + SvelteKit)
3. Optional components: Wagtail CMS, WebSockets (Channels), background workers
4. Infrastructure: PostgreSQL, Redis, object storage
5. CI/CD and deployment pipeline
6. Development and administrative access

Architecture:
- Public users -> Browser -> SvelteKit Frontend -> Django API
- CMS editors -> Browser -> Wagtail Admin (Django)
- Background workers (Procrastinate) -> PostgreSQL/Redis/Storage
- Observability: Sentry
- Deployment: Kerfu Foo, GitHub Actions
- Storage: PostgreSQL, Redis, DigitalOcean Spaces
"""

tm.isOrdered = True
tm.mergeResponses = True

tm.assumptions = [
    "All external communication uses HTTPS with TLS 1.2+",
    "Session authentication implemented using Django session cookies with secure flags",
    "CSRF protection enabled via Django middleware with proper token validation",
    "Redis and PostgreSQL accessible only within private network/VPC",
    "DigitalOcean App Platform provides network isolation and security groups",
    "Public object storage (DigitalOcean Spaces) used only for non-sensitive media assets",
    "Kerfu Foo manages deployment and secrets with secure access controls",
    "GitHub repository uses branch protection and requires code review",
    "Django settings use appropriate security configurations (DEBUG=False in production)",
    "SvelteKit implements proper client-side security controls",
    "All dependencies are regularly updated and monitored for vulnerabilities",
    "Database backups are encrypted and stored securely",
    "Access logs are collected and monitored for suspicious activity",
]


# Boundaries
internet = Boundary("Public Internet")
internet.levels = [1, 2, 3]
internet.inScope = False
internet.maxClassification = Classification.PUBLIC

edge = Boundary("Edge Network / CDN / Load Balancer")
edge.levels = [1, 2]
edge.minTLSVersion = TLSVersion.TLSv12
edge.maxClassification = Classification.RESTRICTED

application = Boundary("Application Runtime (DigitalOcean App Platform)")
application.levels = [1, 2, 3]
application.minTLSVersion = TLSVersion.TLSv12
application.maxClassification = Classification.SENSITIVE
application.description = "Managed container environment for Django and SvelteKit"

internal_services = Boundary("Internal Data Services (VPC)")
internal_services.levels = [2, 3]
internal_services.minTLSVersion = TLSVersion.NONE
internal_services.maxClassification = Classification.SENSITIVE


external_services = Boundary("External SaaS Services")
external_services.levels = [1, 2, 3]
external_services.maxClassification = Classification.SENSITIVE
external_services.minTLSVersion = TLSVersion.TLSv12

administration = Boundary("Administrative Systems")
administration.levels = [3]
administration.maxClassification = Classification.SECRET
administration.minTLSVersion = TLSVersion.TLSv12

supply_chain = Boundary("Software Supply Chain")
supply_chain.levels = [3]
supply_chain.maxClassification = Classification.SENSITIVE
supply_chain.minTLSVersion = TLSVersion.TLSv12

dev_environment = Boundary("Development Environment")
dev_environment.levels = [5]
dev_environment.maxClassification = Classification.RESTRICTED

# Actors
Attacker = Actor("Malicious Actor")
Attacker.levels = [0]
Attacker.inBoundary = internet
Attacker.maxClassification = Classification.UNKNOWN

User = Actor("Public User")
User.levels = [1]
User.inBoundary = internet
User.maxClassification = Classification.PUBLIC

AuthenticatedUser = Actor("Authenticated User")
AuthenticatedUser.levels = [1]  # Same plane as Public User
AuthenticatedUser.inBoundary = internet
AuthenticatedUser.maxClassification = Classification.RESTRICTED

Editor = Actor("CMS Editor")
Editor.levels = [2]  # Slightly "deeper" or grouped separately
Editor.inBoundary = internet
Editor.maxClassification = Classification.SENSITIVE

Developer = Actor("Developer")
Developer.levels = [2]
Developer.inBoundary = dev_environment
Developer.maxClassification = Classification.SENSITIVE

PlatformAdmin = Actor("Platform Administrator")
PlatformAdmin.levels = [3]
PlatformAdmin.inBoundary = administration
PlatformAdmin.maxClassification = Classification.SECRET

# Processes
Frontend = Process("SvelteKit Frontend")
Frontend.inBoundary = application
Frontend.levels = [2]
Frontend.OS = "Linux/Docker"
Frontend.allowsClientSideScripting = True
Frontend.codeType = "Managed"
Frontend.implementsAPI = False
Frontend.maxClassification = Classification.SENSITIVE
Frontend.minTLSVersion = TLSVersion.TLSv12
Frontend.tracksExecutionFlow = True
Frontend.usesEnvironmentVariables = True  # Model W uses env for config
# Security Controls
Frontend.controls.implementsCSRFToken = False
Frontend.controls.checksInputBounds = True
Frontend.controls.encryptsSessionData = True  # Django session encryption
Frontend.controls.usesStrongSessionIdentifiers = True  # Django session security
Frontend.controls.usesSecureFunctions = True
Frontend.controls.validatesInput = True

Backend = Process("Django API")
Backend.inBoundary = application
Backend.levels = [2]
Backend.OS = "Linux/Docker"
Backend.allowsClientSideScripting = False
Backend.codeType = "Managed"
Backend.implementsAPI = True
Backend.maxClassification = Classification.SENSITIVE
Backend.minTLSVersion = TLSVersion.TLSv12
Backend.tracksExecutionFlow = True
Backend.usesEnvironmentVariables = True
# Security Controls
Backend.controls.implementsAuthenticationScheme = True  # Django auth
Backend.controls.implementsCSRFToken = True  # Django CSRF protection
Backend.controls.implementsServerSideValidation = True  # Django forms/DRF serializers
Backend.controls.validatesInput = True  # Input validation
Backend.controls.sanitizesInput = True  # Django template auto-escaping
Backend.controls.encryptsSessionData = True  # Django session encryption
Backend.controls.usesStrongSessionIdentifiers = True  # Django session security
Backend.controls.checksInputBounds = True  # Django form field validation
Backend.controls.usesSecureFunctions = True

CMS = Process("Wagtail Admin")
CMS.inBoundary = application
CMS.levels = [3]
CMS.codeType = "Managed"
CMS.implementsAPI = False
CMS.allowsClientSideScripting = True  # Wagtail admin uses significant JS
CMS.maxClassification = Classification.SENSITIVE
# Security Controls
CMS.controls.implementsAuthenticationScheme = True  # Django admin auth required
CMS.controls.implementsPOLP = True  # Wagtail permission system
CMS.controls.hasAccessControl = True  # Admin interface access control
CMS.controls.usesMFA = False

Worker = Process("Background Worker (Procrastinate)")
Worker.inBoundary = application
Worker.levels = [2]
Worker.OS = "Linux/Docker"
Worker.codeType = "Managed"
Worker.handlesResources = True  # Handles file system/storage tasks
Worker.usesEnvironmentVariables = True


# Datastores
Postgres = Datastore("PostgreSQL Database")
Postgres.inBoundary = internal_services
# Data Sensitivity Properties
Postgres.isShared = True  # Multiple processes (Backend, CMS, Worker) access
Postgres.storesPII = True  # Triggers privacy/GDPR related threats
Postgres.storesSensitiveData = True  # Marks this as a high-value target for attackers
# Architectural Properties
Postgres.hasWriteAccess = True  # Processes connecting to it can modify data
Postgres.isSQL = True  # Explicitly mark as SQL database
Postgres.onRDS = True  # Even if not AWS, it's a "Managed Service"
Postgres.type = DatastoreType.SQL  # Explicitly set type
# Security Controls
Postgres.controls.isEncryptedAtRest = True  # DigitalOcean managed DB encryption
Postgres.controls.implementsAuthenticationScheme = True  # Database user authentication
Postgres.controls.hasAccessControl = True  # Database permissions/RBAC

Redis = Datastore("Redis Cache / Channels")
Redis.inBoundary = internal_services
# Data Sensitivity Properties
Redis.isShared = True  # Accessed by Backend, Workers, and Channels
Redis.storesPII = False  # Typically used for transient data, not PII
Redis.storesSensitiveData = True  # Because it holds session IDs and transient tokens
# Architectural Properties
Redis.hasWriteAccess = True  # All connected processes can write to it
Redis.isSQL = False  # Overriding the default since it's NoSQL/KV
Redis.onRDS = True  # Marks it as a managed cloud service
Redis.type = DatastoreType.UNKNOWN  # pytm lacks a 'CACHE' type;

Spaces = Datastore("DigitalOcean Spaces Object Storage")
Spaces.inBoundary = external_services
# Data Sensitivity Properties
Spaces.isShared = True  # Accessed by Backend and Workers
Spaces.storesPII = False  # Typically used for media assets, not PII
Spaces.storesSensitiveData = False  # While it can store files, we assume not sensitive
# Architectural Properties
Spaces.hasWriteAccess = True  # Backend/Workers can write
Spaces.isSQL = False
Spaces.onRDS = True  # Treated as a managed cloud service
Spaces.type = DatastoreType.AWS_S3  # Spaces uses the S3-compatible API

# External Entities
Browser = ExternalEntity("User Browser")
Browser.inBoundary = internet
Browser.levels = [1]
Browser.OS = "Various"

Sentry = ExternalEntity("Sentry Monitoring")
Sentry.inBoundary = external_services
Sentry.description = "SaaS Error tracking and performance monitoring"
Sentry.OS = "SaaS"

Kerfu = ExternalEntity("Kerfu Foo Deployment Platform")
Kerfu.inBoundary = administration
Kerfu.description = "Deployment orchestration and secret management"
Kerfu.OS = "Linux"
Kerfu.handlesResources = True

GitHub = ExternalEntity("GitHub Source Control")
GitHub.inBoundary = supply_chain
GitHub.description = "Remote VCS and pull request management"
GitHub.OS = "SaaS"

CI = ExternalEntity("CI/CD Pipeline")
CI.inBoundary = supply_chain
CI.description = "Automated build and test environment"
CI.inScope = True

# Data
user_session = Data(
    "User Session Cookie",
    description="Django session ID used for authentication",
    classification=Classification.SENSITIVE,
    isPII=False,
    isCredentials=True,
    credentialsLife=Lifetime.SHORT,
    isStored=True,
    isSourceEncryptedAtRest=True,
    isDestEncryptedAtRest=True,
)

user_credentials = Data(
    "User Credentials",
    description="Username and Password for login",
    classification=Classification.SENSITIVE,
    isPII=True,
    isCredentials=True,
    credentialsLife=Lifetime.MANUAL,
    isStored=True,
    isSourceEncryptedAtRest=False,  # Often cleartext in memory during login
    isDestEncryptedAtRest=True,
)

app_content = Data(
    "Application Content",
    description="General CMS content and public data",
    classification=Classification.PUBLIC,
    isPII=False,
    isCredentials=False,
    isStored=True,
)

pii_data = Data(
    "User Profile Data",
    description="Names, emails, and profile information",
    classification=Classification.SENSITIVE,
    isPII=True,
    isCredentials=False,
    isStored=True,
    isDestEncryptedAtRest=True,
)

db_connection_params = Data(
    "Database Secrets",
    description="Credentials used by Django to connect to Postgres/Redis",
    classification=Classification.RESTRICTED,
    isPII=False,
    isCredentials=True,
    credentialsLife=Lifetime.HARDCODED,
    isStored=True,
    isSourceEncryptedAtRest=True,
)

error_logs = Data(
    "Error Traces",
    description="Stack traces and debug info sent to Sentry",
    classification=Classification.SENSITIVE,
    isPII=True,
    isCredentials=False,
    isStored=True,
)

file_uploads = Data(
    "Uploaded Files",
    description="User-uploaded images, documents, and media files",
    classification=Classification.RESTRICTED,
    isPII=False,  # Files themselves may contain PII but are opaque to system
    isCredentials=False,
    isStored=True,
    isSourceEncryptedAtRest=True,  # Encrypted in transit to storage
)

background_job_data = Data(
    "Background Job Parameters",
    description="Data passed to background workers for processing",
    classification=Classification.SENSITIVE,
    isPII=True,  # May contain user data
    isCredentials=False,
    isStored=True,
    isSourceEncryptedAtRest=True,
)

api_request_data = Data(
    "API Request/Response",
    description="Non-sensitive API payloads and responses",
    classification=Classification.PUBLIC,
    isPII=False,
    isCredentials=False,
    isStored=False,  # Typically not stored long-term
)

config_secrets = Data(
    "Configuration Secrets",
    description="Environment variables, API keys, and service credentials",
    classification=Classification.SECRET,
    isPII=False,
    isCredentials=True,
    credentialsLife=Lifetime.HARDCODED,
    isStored=True,
    isSourceEncryptedAtRest=True,  # Should be encrypted in secret manager
)


# Dataflows
user_to_browser = Dataflow(User, Browser, "User interaction")
user_to_browser.note = "Physical/UI interaction via input devices"

# Browser -> Frontend (HTTPS via DigitalOcean edge)
browser_to_frontend = Dataflow(Browser, Frontend, "HTTPS request to SvelteKit")
browser_to_frontend.data = [api_request_data, user_session]
browser_to_frontend.protocol = "HTTPS"
browser_to_frontend.dstPort = 443
browser_to_frontend.tlsVersion = TLSVersion.TLSv12
browser_to_frontend.implementsCommunicationProtocol = True
browser_to_frontend.note = "TLS termination at DigitalOcean edge"
# Security Controls
browser_to_frontend.controls.isEncrypted = True  # HTTPS encryption
browser_to_frontend.controls.authenticatesDestination = (
    True  # TLS certificate validation
)
browser_to_frontend.controls.checksDestinationRevocation = True  # OCSP/CRL checking

# Browser -> Backend (HTTPS via DigitalOcean edge)
browser_to_backend = Dataflow(Browser, Backend, "HTTPS request to Django API")
browser_to_backend.data = [
    api_request_data,
    user_session,
    user_credentials,
    file_uploads,
]
browser_to_backend.protocol = "HTTPS"
browser_to_backend.dstPort = 443
browser_to_backend.tlsVersion = TLSVersion.TLSv12
browser_to_backend.implementsCommunicationProtocol = True
browser_to_backend.note = "TLS termination at DigitalOcean edge"
# Security Controls
browser_to_backend.controls.isEncrypted = True  # HTTPS encryption
browser_to_backend.controls.authenticatesDestination = (
    True  # TLS certificate validation
)
browser_to_backend.controls.validatesInput = True  # Backend validates all input

# Browser -> CMS (HTTPS via DigitalOcean edge)
browser_to_cms = Dataflow(Browser, CMS, "HTTPS request to Wagtail Admin")
browser_to_cms.data = [user_credentials, file_uploads, app_content]
browser_to_cms.protocol = "HTTPS"
browser_to_cms.dstPort = 443
browser_to_cms.tlsVersion = TLSVersion.TLSv12
browser_to_cms.severity = 2  # Elevated risk due to administrative nature
browser_to_cms.implementsCommunicationProtocol = True
browser_to_cms.note = "Admin interface via DigitalOcean edge"
# Security Controls
browser_to_cms.controls.isEncrypted = True  # HTTPS encryption
browser_to_cms.controls.authenticatesDestination = True  # TLS certificate validation

cms_db = Dataflow(CMS, Postgres, "CMS content read/write")
cms_db.data = [app_content]
cms_db.protocol = "PostgreSQL"
cms_db.dstPort = 25061
cms_db.tlsVersion = TLSVersion.TLSv12
cms_db.note = "Managed DB connection via TLS (DO requirement)"

backend_db = Dataflow(Backend, Postgres, "Application data queries")
backend_db.data = [pii_data, app_content]
backend_db.protocol = "PostgreSQL"
backend_db.dstPort = 25061
backend_db.tlsVersion = TLSVersion.TLSv12
backend_db.severity = 3  # High severity: contains PII
backend_db.note = "Managed DB connection via TLS (DO requirement)"
# Security Controls
backend_db.controls.isEncrypted = True  # TLS encryption
backend_db.controls.authenticatesSource = True  # Database user authentication
backend_db.controls.authorizesSource = True  # Database permissions
backend_db.controls.usesParameterizedInput = True  # SQL parameterization
backend_db.controls.usesSecureFunctions = True  # Django ORM protections

backend_cache = Dataflow(Backend, Redis, "Caching / channels / session storage")
backend_cache.data = [user_session]
backend_cache.protocol = "Redis"
backend_cache.dstPort = 25061
backend_cache.tlsVersion = TLSVersion.TLSv12
backend_cache.note = "Internal state management with TLS"

frontend_api = Dataflow(Frontend, Backend, "Internal API request")
frontend_api.data = [api_request_data, user_session]
frontend_api.protocol = "HTTP"
frontend_api.dstPort = 8000
frontend_api.tlsVersion = TLSVersion.NONE
frontend_api.note = "Internal platform isolated network communication"

task_dispatch = Dataflow(Backend, Postgres, "Background job dispatch (Procrastinate)")
task_dispatch.data = [background_job_data]
task_dispatch.protocol = "PostgreSQL"
task_dispatch.dstPort = 25061
task_dispatch.note = "Asynchronous task queueing via DB table"

worker_db = Dataflow(Worker, Postgres, "Background job queries")
worker_db.data = [background_job_data, pii_data]
worker_db.protocol = "PostgreSQL"
worker_db.dstPort = 25061
worker_db.tlsVersion = TLSVersion.TLSv12

backend_storage = Dataflow(Backend, Spaces, "Media uploads and asset storage")
backend_storage.data = [file_uploads]
backend_storage.protocol = "HTTPS"
backend_storage.dstPort = 443
backend_storage.tlsVersion = TLSVersion.TLSv12
# Security Controls
backend_storage.controls.isEncrypted = True  # HTTPS encryption
backend_storage.controls.authenticatesSource = True  # S3 access key authentication
backend_storage.controls.authorizesSource = True  # IAM/bucket policies
backend_storage.controls.validatesContentType = True  # File type validation

worker_storage = Dataflow(Worker, Spaces, "File processing output")
worker_storage.data = [file_uploads]
worker_storage.protocol = "HTTPS"
worker_storage.dstPort = 443
worker_storage.tlsVersion = TLSVersion.TLSv12
worker_storage.note = "Background workers writing processed files to storage"


backend_errors = Dataflow(Backend, Sentry, "Application errors and traces")
backend_errors.data = [error_logs]
backend_errors.protocol = "HTTPS"
backend_errors.dstPort = 443
backend_errors.tlsVersion = TLSVersion.TLSv12

admin_to_kerfu = Dataflow(PlatformAdmin, Kerfu, "Administrative access")
admin_to_kerfu.data = [config_secrets]
admin_to_kerfu.protocol = "HTTPS"
admin_to_kerfu.dstPort = 443
admin_to_kerfu.tlsVersion = TLSVersion.TLSv12
admin_to_kerfu.severity = 3

kerfu_deploy = Dataflow(Kerfu, Backend, "Deployments and environment configuration")
kerfu_deploy.protocol = "SSH"
kerfu_deploy.dstPort = 22
kerfu_deploy.data = [db_connection_params, config_secrets]
kerfu_deploy.note = "Includes injection of secrets via environment variables"
kerfu_deploy.severity = 3

developer_commit = Dataflow(Developer, GitHub, "Source code push")
developer_commit.data = [api_request_data]  # Source code changes
developer_commit.protocol = "Git/HTTPS"
developer_commit.dstPort = 443
developer_commit.tlsVersion = TLSVersion.TLSv12
developer_commit.note = "Code review process happens here"

ci_deploy = Dataflow(CI, Kerfu, "Deployment artifacts")
ci_deploy.data = [config_secrets]  # Deployment tokens/secrets
ci_deploy.protocol = "HTTPS"
ci_deploy.dstPort = 443
ci_deploy.tlsVersion = TLSVersion.TLSv12
ci_deploy.severity = 2


class ThreatCounter:
    """
    Helper class to count threats after processing the model.
    If the template engine had a way to do findings.length or something,
    we wouldn't need this, but couldn't find a way to access the findings count.
    """

    def __init__(self, tm_instance):
        """Store a reference to the TM instance to access findings after processing."""
        self.tm = tm_instance

    def __str__(self):
        """Return the count of findings as a string for display in the template."""
        return str(len(self.tm.findings))


if __name__ == "__main__":
    tm.threat_count = ThreatCounter(tm)  # pyright: ignore[reportAttributeAccessIssue]
    tm.process()
