# Generated by Django 4.2.13 on 2024-10-02 16:15

import ___project_name__snake___.apps.cms.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("cms", "0002_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customrendition",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
        migrations.CreateModel(
            name="DemoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="This is a required tagline", max_length=255
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="This is an optional description"
                    ),
                ),
                (
                    "demo_blocks",
                    wagtail.fields.StreamField(
                        [
                            (
                                "DemoBlock",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "tagline",
                                            wagtail.blocks.CharBlock(
                                                help_text="This is a required tagline",
                                                max_length=255,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "description",
                                            ___project_name__snake___.apps.cms.blocks.RichTextBlock(
                                                help_text="This is an optional description",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "demo_sub_blocks",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "DemoSubBlock",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "tagline",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="This is a required tagline",
                                                                        max_length=255,
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    ___project_name__snake___.apps.cms.blocks.RichTextBlock(
                                                                        help_text="This is an optional description",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "image",
                                                                    ___project_name__snake___.apps.cms.blocks.ImageChooserBlock(
                                                                        filters=[
                                                                            (
                                                                                [
                                                                                    "fill-768x150-c100",
                                                                                    "fill-1024x250-c100",
                                                                                ],
                                                                                "(max-width: 767px)",
                                                                                "100vw",
                                                                            ),
                                                                            (
                                                                                [
                                                                                    "fill-512x250-c100",
                                                                                    "fill-1024x250-c100",
                                                                                ],
                                                                                "(max-width: 1023px)",
                                                                                "50vw",
                                                                            ),
                                                                            (
                                                                                [
                                                                                    "fill-360x350-c100",
                                                                                    "fill-640x350-c100",
                                                                                ],
                                                                                "(min-width: 1024px)",
                                                                                "25vw",
                                                                            ),
                                                                        ],
                                                                        help_text="This is an optional image",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "heading_blocks",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "Heading",
                                                                                wagtail.blocks.CharBlock(),
                                                                            )
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    )
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            ___project_name__snake___.apps.cms.blocks.ImageChooserBlock(
                                                help_text="This is an optional image",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demo Page",
                "verbose_name_plural": "Demo Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
